name: Super Linter

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_CHECKOV: false
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
